include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
